### ISSUE TITLE
binary output from 6800 code missing first 48 bytes (zeroes) - yet .lst, s19 and intel output all correct

### ISSUE THREAD

**Issue by stanleyruppert** [Arakula/A09#12]
Ran across an assembly listing, that when compiled has no errors/warnings, the .lst, s19, and hex outputs all show correct bytes in first 48 address locations. but binary output file has zeroes in the first 48 bytes. Same behaviour in v140, 150, and 158. Test code and other 6800 code all generate correct binary output files.  Cannot find why this particular code is troublesome.
assembly command: ./a09 -lJBUG.lst -oM00 -oNUM -oDAT -bJBUG.bin JBUG.ASM
build command: gcc -o a09 a09.c [gcc version 9.2.0, host x86_64 darwin MacOS 10.14]
[JBUG.TXT](https://github.com/Arakula/A09/files/10541890/JBUG.TXT)
![Missing 48bytes](https://user-images.githubusercontent.com/42921460/215641960-663c0c1c-c09f-4c95-80a4-57428d029c52.png)

**Comment by Arakula** [comment]
That's the ORG $A000 section with the RMBs at the end of JBUG.TXT. It gets a bit better if you add -oNFB for this one (which causes the RMB statements to add zeroes at the end of the file instead of overwriting the start), but in general ... well, for the moment, don't let A09 emit binary files with such a layout. Create Intel Hex or Motorola S-Record files and convert these to binary, if that's needed.

**Comment by stanleyruppert** [comment]
Thanks for the explanation on the impact of the RMB section and tip about NFB option! I’ll watch out for similar situations in other vintage codes with like layout.
