### ISSUE TITLE
a09 won't take OPT without leading tab

### ISSUE THREAD

**Issue by raybellis** [Arakula/A09#5]
I tried to use `insert` in `f9dasm` to include the `OPT H03` directive so that I don't need to specify it on the command line.

`a09` then reports this:

```
lo.asm(211) : error 16: Illegal mnemonic in "OPT H03"
```

If I manually insert a leading tab the OPT directive works correctly.

There doesn't seem to be a way to add the leading tab in the `f9dasm` info syntax, even though the manual says "insert any assembler statement or pseudo-op".

I can work around this, of course (by using the command line option).

**Comment by raybellis** [comment]
The other work around I just realised is to add a label to the `include` line in my `.info` file:

```
INSERT 0x0000 OPTS OPT H03
INSERT 0x0000 OPTS OPT TSC
```

(curiously, using 0x0000 makes `f9adsm` put these lines _before_ the "used labels" table, but doesn't increase the size of the binary, with its first `ORG` directive specifying a start address of `0x8000`).

**Comment by Arakula** [comment]
I'd normally add things like that (with leading blanks) by putting lines of the form
`insert 0  \        OPT H03`
(i.e., backslash + as many blanks as you want) into the info file. Backslash+tab should work as well.

**Comment by raybellis** [comment]
Thanks - that works :)

**Comment by Arakula** [comment]
Next version of f9dasm will have a (hopefully) clarifying note in f9dasm.htm:

**_Note:_** wherever _**text**_ requires leading blanks or tabs, it isn't possible to simply put them into the instruction, as f9dasm would discard them. For these cases, simply prepend a '\\' (backslash) to the text, like, for example, in
**insert 0 \        OPT H63**
so that f9dasm knows where text really starts. Despite the similarity, f9dasm doesn't know the range of "C" escape characters; a '\\' simply means "Ignore this backslash, but make sure the next character is part of the text". If you need to have a * as part of the text, it is mandatory to write it as \\*; f9dasm would otherwise assume the line ends at the *, which starts the comment part.

**Comment by raybellis** [comment]
I'm having some odd issues with the backslash which I'll add to the f9dasm project
